name: Automated Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enables manual trigger too

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Serve app
        run: npx http-server . -p 8080 &
      - name: Run Cypress tests
        run: npx cypress run
